
version: '3.8'

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=interview_app
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/interview_app?schema=public
      - JWT_SECRET=interview-app-secret-key-change-in-production
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    restart: always

volumes:
  postgres-data:
